(use-modules (workstation home base))

(make-workstation-home
 #:display-config "WORKSTATION_INTERNAL_OUTPUT=eDP-1
WORKSTATION_EXTERNAL_OUTPUT=HDMI-2
WORKSTATION_MIRROR_MODE=1920x1080
WORKSTATION_MIRROR_RATE=60
")
