# XRender avoids requiring firmware-dependent GPU acceleration on Linux-libre.
backend = "xrender";
vsync = true;
shadow = false;
fading = false;
unredir-if-possible = false;
detect-client-opacity = false;
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = true;
# Override application opacity hints for both focused and unfocused windows.
opacity-rule = [ "100:focused", "100:!focused" ];
