(use-modules (workstation home base))

;; Discover dock connector names; MST suffixes can change on reconnect.
(make-workstation-home
 #:bar-font "DejaVu Sans Mono:size=14"
 #:firefox-scale "1.25"
 #:firefox-touchpad-gestures? #t
 #:pointer-config "WORKSTATION_NATURAL_SCROLL_USB_ID='1133, 49291'
WORKSTATION_NATURAL_SCROLL_TOUCHPAD_ID='10248, 536'
WORKSTATION_TOUCHPAD_TWO_FINGER_CLICK=1
"
 #:keyboard-config "WORKSTATION_SWAP_KEYBOARD_USB_ID='8137, 59591'
"
 #:display-config "WORKSTATION_DISPLAY_POLICY=mirror
WORKSTATION_INTERNAL_OUTPUT=auto
WORKSTATION_EXTERNAL_OUTPUT=auto
WORKSTATION_MIRROR_MODE=1920x1080
WORKSTATION_MIRROR_RATE=60
WORKSTATION_EXTERNAL_RATE=120
WORKSTATION_INTERNAL_MODE=1920x1200
WORKSTATION_INTERNAL_RATE=60
")
