(use-modules (gnu) (gnu home) (gnu home services) (gnu services) (guix packages)
             ((gnu packages linux) #:prefix libre:)
             ((nongnu packages linux) #:prefix nongnu:)
             (workstation system base)
             (workstation packages oxwm) (workstation packages codex))

(define system (primitive-load "hosts/t490/system.scm"))
(define home (primitive-load "hosts/t490/home.scm"))
(unless (string=? (operating-system-host-name system) "t490")
  (error "Unexpected hostname"))
(unless (and (eq? (operating-system-kernel system) nongnu:linux)
             (equal? (operating-system-firmware system)
                     (cons nongnu:iwlwifi-firmware %base-firmware)))
  (error "T490 must use the explicit Linux and Intel Wi-Fi exception"))
(unless (and (eq? (operating-system-kernel base-operating-system)
                  libre:linux-libre)
             (equal? (operating-system-firmware base-operating-system)
                     %base-firmware))
  (error "Shared defaults must retain Linux-libre and free firmware"))
;; Folding catches missing or duplicate service dependencies, not just syntax.
(fold-services (operating-system-services system))
(fold-services (home-environment-services home)
               #:target-type home-service-type)
(for-each (lambda (entry)
            (let ((package (if (pair? entry) (car entry) entry)))
              (format #t "~a@~a\n" (package-name package) (package-version package))))
          (cons* oxwm-source codex-source (home-environment-packages home)))
(display "T490 system and Home configuration evaluated.\n")
